name: Merge latest release from main to production Branch

on:
  # workflow_dispatch:   #Manual trigger for testing
  release:
    types: [published]  #Triggers when a release is published

jobs:
  release-merge-to-production:
    runs-on: ubuntu-latest

    steps:
      # Step to retrieve the latest release version
      - name: Get latest release version
        id: get_release
        run: |
          echo "name=version::$(curl -sSL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')" >> $GITHUB_OUTPUT
          
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to create a pull request
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge latest release into production branch'
          title: 'Merge Latest Release: ${{ steps.get_release.outputs.version }}'
          body: 'This pull request merges the latest release into the production branch.'
          branch: production 
          base: master
          head: ${{ steps.get_release.outputs.version }} # Checkout the latest release tag from the main branch
